name: BedWars
version: ${project.version}
main: me.horiciastko.bedwars.BedWars
api-version: '1.13'
softdepend: [PlaceholderAPI, Citizens, Vault]

commands:
  bw:
    description: Main BedWars command
    aliases: [bedwars]
    usage: /bw <subcommand>

permissions:
  bedwars.use:
    description: Allows the usage of basic BedWars commands like /bw join or /bw leave.
    default: true
  bedwars.admin:
    description: Full administrator access to all plugin features and commands.
    default: op
  bedwars.setup:
    description: Ability to create, edit, and manage BedWars arenas.
    default: op
  bedwars.command.rejoin:
    description: Allows the player to rejoin a game they recently disconnected from.
    default: true
  bedwars.command.reload:
    description: Allows the player to reload the plugin configuration.
    default: op
  bedwars.command.lang:
    description: Allows administrators to change the global language of the plugin.
    default: op
